### ISSUE TITLE
Extension does not lint

### ISSUE THREAD

**Issue by coderNeos** [Microsoft/vscode-jshint#60]
Issue Type: <b>Bug</b>

After updating to latest version of vscode, extension does not lint my code. 

Also when i try to run command 'jshint.showOutputChannel', I get an error:
Running the contributed command:'jshint.showOutputChannel' failed.

It seems that something is not working at all.

Extension version: 0.10.18
VS Code version: Code 1.23.1 (d0182c3417d225529c6d5ad24b7572815d0de9ac, 2018-05-10T17:11:17.614Z)
OS version: Windows_NT x64 10.0.17134

**Comment by RMacfarlane** [comment]
Thanks for reporting. The `jshint.showOutputChannel` command should be available after the extension is activated by opening a `.js` file, so it sounds like the extension isn't activating at all.

Can you take a look at the "Log (Extension Host)" output channel after you have started VSCode and opened a `.js` file?
![screen shot 2018-05-18 at 10 04 37 am](https://user-images.githubusercontent.com/3672607/40247928-02daa024-5a83-11e8-92db-fbe698b1471d.png)

**Comment by kibobe04** [comment]
```log
C:\Users\user\.vscode\extensions\dbaeumer.jshint-0.10.18\jshint\out\extension
[2018-05-19 10:16:09.779] [exthost1] [info] eager extensions activated
[2018-05-19 10:16:45.482] [exthost1] [info] ExtensionService#_doActivateExtension vscode.extension-editing {"startup":false,"activationEvent":"onLanguage:typescript"}
[2018-05-19 10:16:45.482] [exthost1] [info] ExtensionService#loadCommonJSModule c:\Program Files\Microsoft VS Code\resources\app\extensions\extension-editing\out\extension
[2018-05-19 10:16:50.889] [exthost1] [error] Error: Channel has been closed
    at e.validate (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:591)
    at e.show (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:554:379)
    at context.subscriptions.push.vscode_1.commands.registerCommand (C:\Users\user\.vscode\extensions\dbaeumer.jshint-0.10.18\jshint\out\extension.js:48:198)
    at e._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:704)
    at e.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:141)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
 jshint.showOutputChannel
```
