### ISSUE TITLE
events.js:167

### ISSUE THREAD

**Issue by danka199** [microsoft/vscode-jshint#78]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\Users\danka\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:40:16 AM] Connection to server got closed. Server will restart.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\Users\danka\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:40:17 AM] Connection to server got closed. Server will restart.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\Users\danka\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:40:19 AM] Connection to server got closed. Server will restart.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\Users\danka\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 11:40:21 AM] Connection to server got closed. Server will restart.
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\Users\danka\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Error - 11:40:23 AM] Connection to server got closed. Server will not be restarted.

**Comment by RMacfarlane** [comment]
@danka199 Can you provide some more details?

- What version of the extension are you using?
- What were you doing prior to seeing this error?
- Can you consistently reproduce this error?

**Comment by danka199** [comment]
Everything happened during installation of the extension of jshint, and I received the same error every time. My vscode was empty during the installation. 
    En martes, 8 de octubre de 2019 18:34:09 CEST, Rachel Macfarlane <notifications@github.com> escribió:  
 
 
@danka199 Can you provide some more details?
   
   - What version of the extension are you using?
   - What were you doing prior to seeing this error?
   - Can you consistently reproduce this error?
